[project]
name = "cli"
version = "0.2.0"
description = "The Slate command line interface — slate run, build, check, and more "
entry = "source/main.slt"

[build]
bin = "slate"
target = "x86-64-v3"
opt = "release-fast"

[deps]
slate = { git = "https://github.com/slatelang-dev/slate" }
compiler = { git = "https://github.com/slatelang-dev/compiler" }
runtime = { git = "https://github.com/slatelang-dev/runtime" }
