[project]
name = "cli"
version = "0.1.0"
description = ""
entry = "source/main.slt"
bin = "slate"

[deps]
slate = { git = "https://github.com/slatelang-dev/slate" }
compiler = { git = "https://github.com/slatelang-dev/compiler" }
runtime = { git = "https://github.com/slatelang-dev/runtime" }
